### ISSUE TITLE
Truck tour - hackerrank problem

### ISSUE THREAD

**Issue by tajuddinkhandaker** [charles-wangkai/hackerrank#16]
Hello,
Did your "Truck Tour" problem solution passed all test cases? It seems may fail in many cases. If last petrol pump loads still causes fuel negative then where it should point?

**Comment by charles-wangkai** [comment]
I just verified my solution (https://github.com/charles-wangkai/hackerrank/blob/e3fa37555f5cb5551bb3bdaba8a64710437b24a9/truck-tour/Solution.java) still passed all test cases. Thanks.
