### ISSUE TITLE
This code is giving wrong output

### ISSUE THREAD

**Issue by shihabcse1** [charles-wangkai/hackerrank#17]
**It can be like this:**

import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class Solution {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);

		Map<String, String> name2phone = new HashMap<String, String>();

		int n = sc.nextInt();
		sc.nextLine();

		for (int i = 0; i < n; i++) {
			String name = sc.nextLine();
			String phone = sc.nextLine();

			name2phone.put(name, phone);
		}

		while (sc.hasNext()) {
			String name = sc.nextLine();

			if (name2phone.containsKey(name)) {
				System.out.println(name + "=" + name2phone.get(name));
			} else {
				System.out.println("Not found");
			}
		}

		sc.close();
	}
}

**Just need to do a little change. Thanks.**

**Comment by charles-wangkai** [comment]
I just verified my solution (https://github.com/charles-wangkai/hackerrank/blob/632fab77386b9dea9c0d118ca3b2c01caf91b9a8/30-dictionaries-and-maps/Solution.java) still passed all test cases. Thanks.

**Comment by shihabcse1** [comment]
But I get the wrong answer when I submit the same code of you.

**Comment by charles-wangkai** [comment]
But it's fine at my side.

![Screenshot_2020-05-11 Day 8 Dictionaries and Maps HackerRank](https://user-images.githubusercontent.com/8757419/81533811-6e6ae500-9399-11ea-887b-b81fbdd2fc0a.png)

**Comment by shihabcse1** [comment]
Okay got it. Thank you.
