### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by nancyp321** [charles-wangkai/hackerrank#2]
In line 21 and line 22 in the main code of even tree,write u1-1 and vi-1 instead of ui and vi,since they are giving out of bounds exception.
`adjacentLists[ui-1].add(vi-1);
			adjacentLists[vi-1].add(ui-1);`

**Comment by charles-wangkai** [comment]
No, I just resubmitted the original code and it passed all test cases correctly. Please note the line 14 `List<Integer>[] adjacentLists = new List[N + 1];`, the size of the array is `N + 1` instead of `N`.

**Comment by nancyp321** [comment]
Oh sorry i didnt notice that ...My bad

**Comment by charles-wangkai** [comment]
Never mind. Thanks all the same :-)
