### ISSUE TITLE
I did same implementation in python but it is not working in some cases can you tell me what I am missing

### ISSUE THREAD

**Issue by hetjagani** [charles-wangkai/hackerrank#6]
`#!/bin/python3

import sys
import math

def encryption(s):
    L = len(s)
    r = math.floor(math.sqrt(L)) #2
    c = math.ceil(math.sqrt(L)) #3
    arr = []
    n=0
    for i in range(r):
        a = []
        for j in range(c):
            if n < L:
                a.append(s[n])
            else:
                break
            n+=1
        arr.append(a)
    print(arr)
    resStr = ''
    for i in range(c):
        for j in range(r):
            try:
                resStr += arr[j][i]
            except IndexError:
                break
        resStr += ' '
    return resStr

if __name__ == "__main__":
    s = input().strip()
    result = encryption(s)
    print(result)
`

**Comment by charles-wangkai** [comment]
What's the problem URL that you're trying to solve?

**Comment by charles-wangkai** [comment]
I close this for it's not a real issue.
